# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/DELL/Desktop/xilinx_uart/xilinx_uart_final/drawsnake/Lab_13.srcs/sources_1/ip/body_R/body_R.xci
# IP: The module: 'body_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/xilinx_uart/xilinx_uart_final/drawsnake/Lab_13.srcs/sources_1/ip/body_R/body_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'body_R'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/DELL/Desktop/xilinx_uart/xilinx_uart_final/drawsnake/Lab_13.srcs/sources_1/ip/body_R/body_R.xci
# IP: The module: 'body_R' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/DELL/Desktop/xilinx_uart/xilinx_uart_final/drawsnake/Lab_13.srcs/sources_1/ip/body_R/body_R_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'body_R'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
